version: "3.9"
volumes:
  playlists:
services:
  wifi-connect:
    container_name: wifi-connect
    build: wifi-connect
    network_mode: "host"
    privileged: true
    #cap_add:
    #  - NET_ADMIN
    volumes:
     - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
